### ISSUE TITLE
Comma-separated selectors

### ISSUE THREAD

**Issue by cyouh95** [SWAAGMAN/prj-rev-bwfs-dasmoto#4]
You could use comma-separated selectors to specify shared properties for multiple elements at once:

```css
h1, h2, .blue {
  font-weight: bold;
}
```

https://github.com/SWAAGMAN/prj-rev-bwfs-dasmoto/blob/master/DasA%26C/rss/index.css#L5-L22
